"""
Chronis Task 3 — Team C Day 4: Crash-Log Audit.

Audits crash logs generated by Task 2's fuzzing runs and confirms zero user
data appears in any of them — daemon state only, as required by Rule 3 and
the privacy design.

A crash log that leaked heart rate, audio energy, raw sensor values, or any
user-identifying content would be a privacy violation even in a debug context.
"""

import re
from dataclasses import dataclass, field
from typing import List


# Patterns that would indicate ACTUAL user data VALUES leaked into a log.
# These require an actual numeric/string value assignment, not just a field
# name appearing in a fuzz-category label like "impossible_hr_jump".
USER_DATA_PATTERNS = [
    (r"heart_rate_bpm['\"]?\s*[=:]\s*\d+\.\d+", "leaked heart rate value"),
    (r"audio_energy['\"]?\s*[=:]\s*0\.\d{2,}", "leaked audio energy value"),
    (r"face_expression['\"]?\s*[=:]\s*['\"](smiling|surprised|laughing|neutral)['\"]",
     "leaked facial expression"),
    (r"\bnote['\"]?\s*[=:]\s*['\"][A-Za-z].{5,}['\"]", "leaked annotation text"),
    (r"wifi_credentials['\"]?\s*[=:]\s*['\"].+['\"]", "leaked WiFi credentials"),
    (r"\bssid['\"]?\s*[=:]\s*['\"].+['\"]", "leaked network name"),
    (r"spo2_percent['\"]?\s*[=:]\s*\d+\.\d+", "leaked SpO2 value"),
]

# Patterns that are OK — daemon state, not user data
ALLOWED_PATTERNS = [
    "SensorStatus", "UNAVAILABLE", "I2C_TIMEOUT", "Severity",
    "MotionState", "WornState", "Level.L", "traceback",
    "OverflowError", "ValueError", "TypeError",
]


@dataclass
class AuditFinding:
    log_index: int
    leaked: bool
    matched_pattern: str = ""
    snippet: str = ""


@dataclass
class CrashLogAudit:
    total_logs: int = 0
    clean_logs: int = 0
    leaked_logs: int = 0
    findings: List[AuditFinding] = field(default_factory=list)

    def summary(self) -> str:
        return (f"Audited {self.total_logs} crash logs | "
                f"{self.clean_logs} clean | {self.leaked_logs} with leaks")


def audit_crash_log(log_text: str, index: int) -> AuditFinding:
    """Check a single crash log for user data leakage."""
    for pattern, desc in USER_DATA_PATTERNS:
        m = re.search(pattern, log_text, re.IGNORECASE)
        if m:
            return AuditFinding(
                log_index=index, leaked=True,
                matched_pattern=desc,
                snippet=log_text[max(0, m.start()-20):m.end()+20],
            )
    return AuditFinding(log_index=index, leaked=False)


def audit_fuzzing_crash_logs(verbose: bool = True) -> CrashLogAudit:
    """
    Generate crash logs by re-running Task 2's fuzzing, then audit each one.
    Confirms daemon state only, never user data.
    """
    import sys, os
    ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    sys.path.insert(0, os.path.join(ROOT, "hw-track-1-sensors"))
    sys.path.insert(0, os.path.join(ROOT, "hw-track-3-connectivity"))
    sys.path.insert(0, os.path.join(ROOT, "hardening-security"))

    from fuzzing.fuzz_harness import run_all_fuzzers, Severity

    reports = run_all_fuzzers(verbose=False)

    # Collect all crash/error detail strings (these are the "crash logs")
    crash_logs = []
    for report in reports:
        for result in report.results:
            if result.exception or result.detail:
                # a crash log = exception + detail (daemon state at failure)
                log = f"{result.daemon_name} | {result.fuzz_category} | " \
                      f"{result.exception or ''} | {result.detail}"
                crash_logs.append(log)

    # Also add synthetic crash logs that SHOULD be clean (daemon state)
    synthetic_clean = [
        "motion_daemon | nan_accel_x | ValueError: reading rejected | "
        "MotionState.UNAVAILABLE status=UNAVAILABLE reason=I2C_TIMEOUT",
        "worn_detector | all_nan | vote_score computation | WornState.WORN "
        "components normalized, no user values logged",
        "state_machine | rapid_cycling | Level.L2 transition | "
        "hysteresis timer reset, daemon state only",
    ]
    crash_logs.extend(synthetic_clean)

    audit = CrashLogAudit(total_logs=len(crash_logs))

    for i, log in enumerate(crash_logs):
        finding = audit_crash_log(log, i)
        audit.findings.append(finding)
        if finding.leaked:
            audit.leaked_logs += 1
            if verbose:
                print(f"  !! LEAK in log #{i}: {finding.matched_pattern}")
                print(f"     {finding.snippet}")
        else:
            audit.clean_logs += 1

    if verbose:
        print(f"\n{audit.summary()}")

    return audit


if __name__ == "__main__":
    print("=" * 60)
    print("  Chronis Task 3 — Team C: Crash-Log Privacy Audit")
    print("=" * 60)
    audit = audit_fuzzing_crash_logs()
    print("=" * 60)
    verdict = "PASS: no user data in any crash log" if audit.leaked_logs == 0 \
              else f"FAIL: {audit.leaked_logs} logs leaked user data"
    print(f"  {verdict}")
    print("=" * 60)
